version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.8
    steps:
      - run: |
          mkdir -p ~/bin
          echo 'export PATH="$HOME/bin:$PATH"' >> $BASH_ENV
      - run: |
          curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b ~/bin v1.16.0
      - checkout
      - run: make check
      - run: bash <(curl -s https://codecov.io/bash)
      - run: |
          if [ "$CIRCLE_TAG" ]; then
            go get github.com/int128/goxzst
            go get github.com/tcnksm/ghr
            make VERSION="$CIRCLE_TAG" release
          fi

workflows:
  version: 2
  all:
    jobs:
      - build:
          context: open-source
          filters:
            branches:
              only: dummy
