apiVersion: v1
kind: Service
metadata:
  labels:
    app: jira-to-slack
  name: jira-to-slack
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: jira-to-slack
